version: '3.8'
services:
   proxy:
     image: nginx:latest
     ports:
       - 80:80
     volumes:
       - ./ops/apps.conf:/etc/nginx/conf.d/default.conf
   landingpage:
     image: ariretiarno/latihan-nginx:landingpage
#     volumes:
#       - ./nginx-volume:/usr/share/nginx/html
     deploy:
       replicas: 3
       resources:
         limits:
           cpus: 0.1
           memory: 128M
